version: "3.7"
services:
  ui:
    image: registery.exlinetr.com/exlinetr.com:2.0.0
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 0
        delay: 5s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_network"
        - "traefik.http.routers.www_exlinetr_com_ui.service=www_exlinetr_com_ui"
        - "traefik.http.routers.www_exlinetr_com_ui.rule=Host(`www.exlinetr.com`)||Host(`exlinetr.com`)"
        - "traefik.http.routers.www_exlinetr_com_ui.entrypoints=web"
        - "traefik.http.services.www_exlinetr_com_ui.loadbalancer.server.port=80"
        - "traefik.http.services.www_exlinetr_com_ui.loadbalancer.server.scheme=http"
    networks:
      - exlinetr-com-ui-net
      - traefik_network

networks:
  exlinetr-com-ui-net:
    name: "exlinetr-com-ui-net"
  traefik_network:
    external: true