version: "3.4"

services:
  ui:
    image: furkaandogan/exlinetr.com:1.0.0
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_network"
        - "traefik.http.routers.www_exlinetr_com_ui.service=www_exlinetr_com_ui"
        - "traefik.http.routers.www_exlinetr_com_ui.rule=Host(`www.exlinetr.com`)||Host(`exlinetr.com`)"
        - "traefik.http.routers.www_exlinetr_com_ui.entrypoints=web"
        - "traefik.http.services.www_exlinetr_com_ui.loadbalancer.server.port=80"
        - "traefik.http.services.www_exlinetr_com_ui.loadbalancer.server.scheme=http"
    networks:
      - traefik_network
    ports:
      - 1000:80


networks:
  traefik_network:
    external: true